esphome:
  name: flowsensing-zb

external_components:
  - source:
      type: local
      path: zigbee_esphome/components
    components: [ zigbee ]

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  partitions: partitions_zb.csv
  framework:
    platform_version: 6.6.0
    type: esp-idf
    version: 5.2.1
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
  variant: esp32c6

# Enable logging
logger:
  hardware_uart: UART0

# Use sensor component to count and send messages
# Is inferior because wont log transitions, logs if switch closed (Could be closed for hours, despite no flow)
sensor:
  - platform: pulse_counter
    pin: GPIO04
    name: "Water Flow Rate"
    unit_of_measurement: "L/min"
    accuracy_decimals: 2
    update_interval: 1s
    total:
      name: "Total Water Flow"
      unit_of_measurement: "L"
      accuracy_decimals: 2
    on_value:
      then:
        - zigbee.setAttr:
            id: zb
            endpoint: 1
            cluster: FLOW_MEASUREMENT
            attribute: 0x0
            value: !lambda "return x;"


zigbee:
  id: "zb"
  endpoints:
    - num: 1
      device_type: SIMPLE_SENSOR
      clusters:
        - id: FLOW_MEASUREMENT
          attributes:
            - id: 0x0
              type: U16
              report: true
              value: 0


