- id: '1733759370366'
  alias: AqaraOFF
  description: ''
  triggers:
  - trigger: mqtt
    topic: zigbee2mqtt/Aqara vibration/vibration
    payload: 'false'
  conditions: []
  actions: []
  mode: single
- id: '1733759438590'
  alias: TuyaRecurringVibrationTRUE
  description: ''
  triggers:
  - trigger: mqtt
    topic: zigbee2mqtt/Tuya_Vibe/vibration
    payload: 'true'
  conditions: []
  actions: []
  mode: single
- id: '1733759438591'
  alias: ZigbeeAvailability
  description: ''
  triggers:
  - trigger: mqtt
    topic: zigbee2mqtt/+/availability
    payload: 'offline'
  conditions: []
  actions:
  - service: logbook.log
    data:
      name: ""
      message: "{{ trigger.topic.split('/')[1] }} is {{ trigger.payload }}  |"
  mode: single
