# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
users: !include users.yaml

#logger:
#  default: debug
  
logbook:
  exclude:
    entities:
      - automation.zigbeeavailability
      
      
recorder:
  db_url: mysql://cole:aaa1aaa@127.0.0.1/hass_db?charset=utf8mb4
  purge_keep_days: 50
  auto_purge: false
  commit_interval: 5

